name: run unit test
on:
 pull_request:
  branches: [ main, dev ]
jobs:
 unit-test:
  runs-on: ubuntu-22.04
  
  strategy:
   matrix:
    node-version: [ 18 ]

  steps:
  - uses: https://github.com/actions/checkout@v3
  - name: Set up Node.js 18
   uses: https://github.com/actions/setup-node@v1
   with:
    node-version: 18
  - name: Install dependencies
   run: npm install
  - name: Run Unit Tests
   run: npm run test:unit