# .gitea/workflows/gitea-ci.yaml
name: Gitea Action Build And Test(YAONG)
run-name: ${{ gitea.actor }} is runs ci pipeline by yaong
on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENCE
      - 'docs/**'
      - 'helm/**'

jobs:
  Gitea-Docker-Build-Push:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64          
          push: true
          tags: gnu96/gitea-docker-build-push-repo:latest