# 워크 플로 이름
name: Java CI/CD with Gradle

# 메인에 푸쉬나 피알되면 이벤트 발생
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

## 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
#       uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#       with:
#         arguments: build
      run : ./gradlew clean build -x test
      
      # 아티팩트 업로드
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cicdsample
        path: build/libs/*.jar
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      ## 빌드했던거 받기
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cicdsample
          
#       - name: Setup SSH
#         uses: webfactory/ssh-agent@v0.5.4
#         with:
#           ssh-private-key: ${{ secrets.SSH_KEY }}
      # 깃허브 액션 러너의 아이피를 얻어온다.
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
      
      # 환경변수 설정 
      - name: docker login Setting environment variables
        env:
          DOCKER_USER: '${{ secrets.DOCKER_USER }}'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Docker Image Build and Registry deploy
        env:
          DOCKERHUB_REGISTRY: yaongdocker
        run: |
          echo $LATEST_TAG
          docker build -t $DOCKERHUB_REGISTRY/echo-demo:latest .
          docker push -a $DOCKERHUB_REGISTRY/echo-demo:latest
          